### ISSUE TITLE
1. Use "style" selectors instead of "tag/id" selectors

### ISSUE THREAD

**Issue by skryvets** [sarahbrawdy/Sarah-Space#1]
It's great that you are learning different selectors (like id selector `#id`, tag selector `header` or nested tag selector `header nav ul`), but in a professional setting styles are almost exclusively are applied via `style` selector. It's not that your approach is not going to work, but using styles it's more accepted practice.

For example, in your HTML file you should add `class="your-style-name"`: 

```html
<header class="header">
      <div class="page-logo">
        <a href="index.html">Sarah's Space</a>
      </div>
      <nav class="navigation">
        <ul class="navigation-list">
          <li class="navigation-item"><a class="navigation-link" href="about.html">About</a></li>
          <li class="navigation-item"><a class="navigation-link" href="crochet.html">Crochet</a></li>
          <li class="navigation-item"><a class="navigation-link" href="coding.html">Coding</a></li>
        </ul>
      </nav>
    </header>
```

while CSS should look like the following:

```CSS 
.header {
/*  ... your styles go here..... */
}
.navigation {
/* ... your styles go here..... */
}
etc...
```

**Comment by sarahbrawdy** [comment]
Complete, I think.
